# Generated by Django 2.2.12 on 2022-02-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroCoches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coche',
            options={'verbose_name': 'coche', 'verbose_name_plural': 'coches'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'marca', 'verbose_name_plural': 'marcas'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name': 'modelo', 'verbose_name_plural': 'modelos'},
        ),
        migrations.AddField(
            model_name='coche',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coche',
            name='fotoCoche',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coche',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='marca',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
